import type { Metadata } from 'next'

import { ReactNode } from 'react'

import { Inter } from 'next/font/google'
import Head from 'next/head'

import './globals.css'

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
  icons: [
    {
      rel: 'icon',
      type: 'image/svg+xml',
      sizes: '24x24',
      url: '/icon.svg',
    },
  ],
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang={'en'}>
    <Head>
      <link rel={'icon'} href={'/icon.svg'} sizes={'any'} type={'image/svg+xml'} />
    </Head>
    <body className={inter.className}>{children}</body>
    </html>
  )
}
